pip install requests

In [ ]:
import requests
import csv

def get_jobs_from_indeed():
    url = "https://indeed12.p.rapidapi.com/jobs/search"
    querystring = {"query": "Information technology", "sort": "date"}

    headers = {
        "x-rapidapi-key": "e46546b67emsh1da2cc270e90508p17c823jsnc5bc19b57230",
        "x-rapidapi-host": "indeed12.p.rapidapi.com"
    }

    with open("jobs_data.csv", mode="w", newline="", encoding="utf-8") as file:
        writer = csv.writer(file)
        # Ghi tiêu đề cột
        writer.writerow(["Job Title", "Location", "Salary"])
        
        page = 1 
        while True:
            querystring["page_id"] = page 
            response = requests.get(url, headers=headers, params=querystring)
            
            if response.status_code == 200:
                data = response.json()
                
    
                if data.get('count', 0) > 0:
                    for job in data.get('hits', []):
                        title = job.get('title', 'Not available')
                        location = job.get('location', 'Not available')
                        salary = job.get('salary', 'Not available')
                        
                        
                        writer.writerow([title, location, salary])
                        
                        
                        print(f"Job Title: {title}")
                        print(f"Location: {location}")
                        print(f"Salary: {salary}")
                        print("----------")
                
            
                next_page_id = data.get('next_page_id')
                if next_page_id:
                    page += 1  
                    print(f"Chuyển sang trang {page}...")
                else:
                    print("Không còn trang tiếp theo.")
                    break  
            else:
                print(f"Lỗi khi lấy dữ liệu: {response.status_code}")
                break


get_jobs_from_indeed()

Lỗi khi lấy dữ liệu: 429

In [ ]:
import requests
import pandas as pd

url = "https://jobs-api14.p.rapidapi.com/v2/list"
headers = {
    "x-rapidapi-key": "e46546b67emsh1da2cc270e90508p17c823jsnc5bc19b57230",
    "x-rapidapi-host": "jobs-api14.p.rapidapi.com"
}

jobs_list = []
page = 1
max_pages = 20  
while page <= max_pages:  
    querystring = {"query": "Web Developer", "location": "United States", "page": page}
    response = requests.get(url, headers=headers, params=querystring)
    
    if response.status_code == 200:
        data = response.json()
        jobs_data = data.get("jobs", [])
        
       
        if not jobs_data:
            print("Đã tải xong tất cả dữ liệu.")
            break
        
        for job in jobs_data:
            jobs_list.append({
                "Title": job.get("title", "Not Available"),
                "Company": job.get("company", "Not Available"),
                "Location": job.get("location", "Not Available"),
                "Description": job.get("description", "Not Available"),
                "Posted Date": job.get("date", "Not Available")
            })
        
        print(f"Đã tải xong trang {page}.")
        page += 1
    else:
        print(f"Lỗi khi tải dữ liệu từ API: {response.status_code}")
        break


df = pd.DataFrame(jobs_list)

print(df)


df.to_csv("jobs_data_limited_pages.csv", index=False, encoding="utf-8")

Đã tải xong trang 1.
Đã tải xong trang 2.
Đã tải xong trang 3.
Đã tải xong trang 4.
Đã tải xong trang 5.
Đã tải xong trang 6.
Đã tải xong trang 7.
Đã tải xong trang 8.
Đã tải xong trang 9.
Đã tải xong trang 10.
Đã tải xong trang 11.
Đã tải xong trang 12.
Đã tải xong trang 13.
Đã tải xong trang 14.
Đã tải xong trang 15.
Đã tải xong trang 16.
Đã tải xong trang 17.
Đã tải xong trang 18.
Đã tải xong trang 19.
Đã tải xong trang 20.
                                                 Title  \
0                               Web Developer (Remote)
1    Fulltime position for Sr. Web Developer with R...
2                                        Web Developer
3                                        Web Developer
4                          Web Developer - Entry Level
..                                                 ...
195                        Web Developer - Entry Level
196                                      Web Developer
197                                      Web Developer
198            Junior Drupal Web Developer (Part-time)
199  Full-Stack Web Developer (Utah residents only;...

                              Company            Location  \
0               Fusion Technology LLC       United States
1            VEAH Consulting Services       Cupertino, CA
2                  Cornell University       United States
3    Virginia Commonwealth University        Richmond, VA
4                       Hardin Design         Madison, WI
..                                ...                 ...
195                     Hardin Design         Madison, WI
196                    Demme Learning     Rohrerstown, PA
197                        McCrometer           Hemet, CA
198  American Institutes for Research       Rockville, MD
199                Smith Johnson Tech  Salt Lake City, UT

                                           Description    Posted Date
0    Fusion Enterprise Solutions is in search for a...  Not Available
1    Position: Sr. Web Developer with ReactJS Exper...  Not Available
2    Web Developer (Remote) *No Visa Sponsorship of...  Not Available
3    Web Developer\n\nBenefits of working at VCU\n\...  Not Available
4    Company Description\n\nAt Hardin Design & Deve...  Not Available
..                                                 ...            ...
195  Company Description\n\nAt Hardin Design & Deve...  Not Available
196  GENERAL ROLE DESCRIPTION\n\nWorking from estab...  Not Available
197  McCrometer (www.mccrometer.com) is a global le...  Not Available
198  Overview\n\nJoin AIR as a part-time Junior Dru...  Not Available
199  • *This role is NOT open to sub-vendors or C2C...  Not Available

[200 rows x 5 columns]

,Title,Company,Location,Description,Posted Date
0,Web Developer (Remote),Fusion Technology LLC,United States,Fusion Enterprise Solutions is in search for a...,Not Available
1,Fulltime position for Sr. Web Developer with R...,VEAH Consulting Services,"Cupertino, CA",Position: Sr. Web Developer with ReactJS Exper...,Not Available
2,Web Developer,Cornell University,United States,Web Developer (Remote) *No Visa Sponsorship of...,Not Available
3,Web Developer,Virginia Commonwealth University,"Richmond, VA",Web Developer\n\nBenefits of working at VCU\n\...,Not Available
4,Web Developer - Entry Level,Hardin Design,"Madison, WI",Company Description\n\nAt Hardin Design & Deve...,Not Available
...,...,...,...,...,...
195,Web Developer - Entry Level,Hardin Design,"Madison, WI",Company Description\n\nAt Hardin Design & Deve...,Not Available
196,Web Developer,Demme Learning,"Rohrerstown, PA",GENERAL ROLE DESCRIPTION\n\nWorking from estab...,Not Available
197,Web Developer,McCrometer,"Hemet, CA",McCrometer (www.mccrometer.com) is a global le...,Not Available
198,Junior Drupal Web Developer (Part-time),American Institutes for Research,"Rockville, MD",Overview\n\nJoin AIR as a part-time Junior Dru...,Not Available
199,Full-Stack Web Developer (Utah residents only;...,Smith Johnson Tech,"Salt Lake City, UT",• *This role is NOT open to sub-vendors or C2C...,Not Available

In [13]:

# Regex để trích xuất lương
salary_regex = r"(\$\d{1,3}(?:,\d{3})*(?:k|K)?|\d{1,3}(?:,\d{3})*(?:k|K)?\s*(USD)?)"

# Regex để trích xuất số năm kinh nghiệm
experience_regex = r"(\d+\+?)\s*(?:years|yrs|year)"

# Thêm cột Salary và Experience
df['Salary'] = df['Description'].str.extract(salary_regex, expand=False)[0]
df['Experience'] = df['Description'].str.extract(experience_regex, expand=False)[0]

In [14]:
df

,Title,Company,Location,Description,Posted Date,Salary,Experience
0,Web Developer (Remote),Fusion Technology LLC,United States,Fusion Enterprise Solutions is in search for a...,Not Available,"$135,000",1
1,Fulltime position for Sr. Web Developer with R...,VEAH Consulting Services,"Cupertino, CA",Position: Sr. Web Developer with ReactJS Exper...,Not Available,5,1
2,Web Developer,Cornell University,United States,Web Developer (Remote) *No Visa Sponsorship of...,Not Available,2,1
3,Web Developer,Virginia Commonwealth University,"Richmond, VA",Web Developer\n\nBenefits of working at VCU\n\...,Not Available,242,1
4,Web Developer - Entry Level,Hardin Design,"Madison, WI",Company Description\n\nAt Hardin Design & Deve...,Not Available,500,1
...,...,...,...,...,...,...,...
195,Web Developer - Entry Level,Hardin Design,"Madison, WI",Company Description\n\nAt Hardin Design & Deve...,Not Available,500,1
196,Web Developer,Demme Learning,"Rohrerstown, PA",GENERAL ROLE DESCRIPTION\n\nWorking from estab...,Not Available,40,1
197,Web Developer,McCrometer,"Hemet, CA",McCrometer (www.mccrometer.com) is a global le...,Not Available,$5,1
198,Junior Drupal Web Developer (Part-time),American Institutes for Research,"Rockville, MD",Overview\n\nJoin AIR as a part-time Junior Dru...,Not Available,194,1
199,Full-Stack Web Developer (Utah residents only;...,Smith Johnson Tech,"Salt Lake City, UT",• *This role is NOT open to sub-vendors or C2C...,Not Available,2,1

In [ ]:
import re
def extract_12_digits(description):
    # Tìm kiếm 12 số ngay sau dấu $
    match = re.search(r'\$(\d{12})', description)
    
    if match:
        return match.group(1)  # Trả về 12 số sau dấu $
    return None  # Nếu không tìm thấy 12 số sau $

# Áp dụng hàm trích xuất 12 số
df['Salary'] = df['Description'].apply(extract_12_digits)
df

,Title,Company,Location,Description,Posted Date,Salary,Experience,Salary_Raw,Salary Range
0,Web Developer (Remote),Fusion Technology LLC,United States,Fusion Enterprise Solutions is in search for a...,Not Available,None,1,"$135,000","(135000, 140000)"
1,Fulltime position for Sr. Web Developer with R...,VEAH Consulting Services,"Cupertino, CA",Position: Sr. Web Developer with ReactJS Exper...,Not Available,None,1,5,5
2,Web Developer,Cornell University,United States,Web Developer (Remote) *No Visa Sponsorship of...,Not Available,None,1,2,2
3,Web Developer,Virginia Commonwealth University,"Richmond, VA",Web Developer\n\nBenefits of working at VCU\n\...,Not Available,None,1,242,242
4,Web Developer - Entry Level,Hardin Design,"Madison, WI",Company Description\n\nAt Hardin Design & Deve...,Not Available,None,1,500,500
...,...,...,...,...,...,...,...,...,...
195,Web Developer - Entry Level,Hardin Design,"Madison, WI",Company Description\n\nAt Hardin Design & Deve...,Not Available,None,1,500,500
196,Web Developer,Demme Learning,"Rohrerstown, PA",GENERAL ROLE DESCRIPTION\n\nWorking from estab...,Not Available,None,1,40,"(33000, 49500)"
197,Web Developer,McCrometer,"Hemet, CA",McCrometer (www.mccrometer.com) is a global le...,Not Available,None,1,$5,"(70000, 90000)"
198,Junior Drupal Web Developer (Part-time),American Institutes for Research,"Rockville, MD",Overview\n\nJoin AIR as a part-time Junior Dru...,Not Available,None,1,194,194
199,Full-Stack Web Developer (Utah residents only;...,Smith Johnson Tech,"Salt Lake City, UT",• *This role is NOT open to sub-vendors or C2C...,Not Available,None,1,2,2

In [ ]:
import re

# Hàm để chiết xuất mức lương từ cột "Description"
def extract_salary(description):
    # Biểu thức chính quy tìm các mức lương
    match = re.search(r'\$[\d,]+(?:\s?-\s?[\d,]+|\sto\s[\d,]+)?', description)
    if match:
        return match.group(0)
    return None
df['Salary'] = df['Description'].apply(extract_salary)
def convert_salary(salary):
    if salary:
        salary = salary.replace('$', '').replace(',', '')
        if 'to' in salary:
            salary = salary.split('to')[0].strip()
        return float(salary)
    return None

df['Salary'] = df['Salary'].apply(convert_salary)

# Lọc các hàng có mức lương thấp hơn 1000

df.loc[df['Salary'] < 1000, 'Salary'] = df.loc[df['Salary'] < 1000, 'Salary_Raw']
df['Salary']

C:\Users\Admin\AppData\Local\Temp\ipykernel_14444\4116424512.py:23: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['$5' '$5' '100 ' '$5' '100 ' '$5' '194' '$5' '$5' '100 ' '$5' '$5' '$5'
 '100 ' '$5' '$5' '$5' '100 ' '$5' '$5' '100 ' '$5' '100 ' '$5' '100 '
 '$5' '100 ' '$5' '$5' '$5' '194']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df['Salary'] < 1000, 'Salary'] = df.loc[df['Salary'] < 1000, 'Salary_Raw']

,Title,Company,Location,Description,Posted Date,Salary,Experience,Salary_Raw,Salary Range
0,Web Developer (Remote),Fusion Technology LLC,United States,Fusion Enterprise Solutions is in search for a...,Not Available,135000.0,1,"$135,000","(135000, 140000)"
1,Fulltime position for Sr. Web Developer with R...,VEAH Consulting Services,"Cupertino, CA",Position: Sr. Web Developer with ReactJS Exper...,Not Available,NaN,1,5,5
2,Web Developer,Cornell University,United States,Web Developer (Remote) *No Visa Sponsorship of...,Not Available,70556.0,1,2,2
3,Web Developer,Virginia Commonwealth University,"Richmond, VA",Web Developer\n\nBenefits of working at VCU\n\...,Not Available,75000.0,1,242,242
4,Web Developer - Entry Level,Hardin Design,"Madison, WI",Company Description\n\nAt Hardin Design & Deve...,Not Available,55000.0,1,500,500
...,...,...,...,...,...,...,...,...,...
195,Web Developer - Entry Level,Hardin Design,"Madison, WI",Company Description\n\nAt Hardin Design & Deve...,Not Available,55000.0,1,500,500
196,Web Developer,Demme Learning,"Rohrerstown, PA",GENERAL ROLE DESCRIPTION\n\nWorking from estab...,Not Available,33000.0,1,40,"(33000, 49500)"
197,Web Developer,McCrometer,"Hemet, CA",McCrometer (www.mccrometer.com) is a global le...,Not Available,$5,1,$5,"(70000, 90000)"
198,Junior Drupal Web Developer (Part-time),American Institutes for Research,"Rockville, MD",Overview\n\nJoin AIR as a part-time Junior Dru...,Not Available,194,1,194,194
199,Full-Stack Web Developer (Utah residents only;...,Smith Johnson Tech,"Salt Lake City, UT",• *This role is NOT open to sub-vendors or C2C...,Not Available,NaN,1,2,2

In [45]:
import re

# Hàm để chiết xuất mức lương từ cột "Description"
def extract_salary(description):
    # Biểu thức chính quy tìm các mức lương
    match = re.search(r'\$[\d,]+(?:\s?-\s?[\d,]+|\sto\s[\d,]+)?', description)
    if match:
        return match.group(0)
    return None

# Áp dụng hàm extract_salary lên cột 'Description'
df['Salary'] = df['Description'].apply(extract_salary)

# Hàm chuyển đổi mức lương từ chuỗi sang kiểu số
def convert_salary(salary):
    if salary:
        salary = salary.replace('$', '').replace(',', '')
        if 'to' in salary:
            salary = salary.split('to')[0].strip()
        return float(salary)
    return None

# Áp dụng hàm convert_salary lên cột 'Salary'
df['Salary'] = df['Salary'].apply(convert_salary)

# Kiểm tra cột 'Salary_Raw' tồn tại và có dữ liệu hợp lệ
if 'Salary_Raw' in df.columns:
    # Lọc các hàng có mức lương thấp hơn 1000 và thay thế giá trị của 'Salary'
    df.loc[df['Salary'] < 1000, 'Salary'] = df.loc[df['Salary'] < 1000, 'Salary Range']

# Kiểm tra lại cột 'Salary' sau khi thay thế
df

C:\Users\Admin\AppData\Local\Temp\ipykernel_14444\2660992406.py:29: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[(70000, 90000) (70000, 90000) '100 ' (70000, 90000) '100 ' (70000, 90000)
 '194' (70000, 90000) (70000, 90000) '100 ' (70000, 90000) (70000, 90000)
 (70000, 90000) '100 ' (70000, 90000) (70000, 90000) (70000, 90000) '100 '
 (70000, 90000) (70000, 90000) '100 ' (70000, 90000) '100 ' (70000, 90000)
 '100 ' (70000, 90000) '100 ' (70000, 90000) (70000, 90000) (70000, 90000)
 '194']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df['Salary'] < 1000, 'Salary'] = df.loc[df['Salary'] < 1000, 'Salary Range']

,Title,Company,Location,Description,Posted Date,Salary,Experience,Salary_Raw,Salary Range
0,Web Developer (Remote),Fusion Technology LLC,United States,Fusion Enterprise Solutions is in search for a...,Not Available,135000.0,1,"$135,000","(135000, 140000)"
1,Fulltime position for Sr. Web Developer with R...,VEAH Consulting Services,"Cupertino, CA",Position: Sr. Web Developer with ReactJS Exper...,Not Available,NaN,1,5,5
2,Web Developer,Cornell University,United States,Web Developer (Remote) *No Visa Sponsorship of...,Not Available,70556.0,1,2,2
3,Web Developer,Virginia Commonwealth University,"Richmond, VA",Web Developer\n\nBenefits of working at VCU\n\...,Not Available,75000.0,1,242,242
4,Web Developer - Entry Level,Hardin Design,"Madison, WI",Company Description\n\nAt Hardin Design & Deve...,Not Available,55000.0,1,500,500
...,...,...,...,...,...,...,...,...,...
195,Web Developer - Entry Level,Hardin Design,"Madison, WI",Company Description\n\nAt Hardin Design & Deve...,Not Available,55000.0,1,500,500
196,Web Developer,Demme Learning,"Rohrerstown, PA",GENERAL ROLE DESCRIPTION\n\nWorking from estab...,Not Available,33000.0,1,40,"(33000, 49500)"
197,Web Developer,McCrometer,"Hemet, CA",McCrometer (www.mccrometer.com) is a global le...,Not Available,"(70000, 90000)",1,$5,"(70000, 90000)"
198,Junior Drupal Web Developer (Part-time),American Institutes for Research,"Rockville, MD",Overview\n\nJoin AIR as a part-time Junior Dru...,Not Available,194,1,194,194
199,Full-Stack Web Developer (Utah residents only;...,Smith Johnson Tech,"Salt Lake City, UT",• *This role is NOT open to sub-vendors or C2C...,Not Available,NaN,1,2,2

In [47]:
# Kiểm tra các giá trị NaN trong cột 'Salary'
df[df['Salary'].isna()]

,Title,Company,Location,Description,Posted Date,Salary,Experience,Salary_Raw,Salary Range
1,Fulltime position for Sr. Web Developer with R...,VEAH Consulting Services,"Cupertino, CA",Position: Sr. Web Developer with ReactJS Exper...,Not Available,NaN,1,5,5
7,Full-Stack Web Developer (Utah residents only;...,Smith Johnson Tech,"Salt Lake City, UT",• *This role is NOT open to sub-vendors or C2C...,Not Available,NaN,1,2,2
8,Senior Java Web Developer - IT (Information Te...,Societe Generale,"New York, NY",Responsibilities\n\nGlobal Banking Technology ...,Not Available,NaN,1,2,2
9,Web Application Developer,New York City,"Queens, NY",Hours: Full-Time – 35 Hours\nWork Location: 30...,Not Available,NaN,1,35,35
11,Fulltime position for Sr. Web Developer with R...,VEAH Consulting Services,"Cupertino, CA",Position: Sr. Web Developer with ReactJS Exper...,Not Available,NaN,1,5,5
...,...,...,...,...,...,...,...,...,...
188,Web Application Developer,New York City,"Queens, NY",Hours: Full-Time – 35 Hours\nWork Location: 30...,Not Available,NaN,1,35,35
189,Senior Java Web Developer - IT (Information Te...,Societe Generale,"New York, NY",Responsibilities\n\nGlobal Banking Technology ...,Not Available,NaN,1,2,2
191,Web Developer,EnerSys Delaware Inc.,"Reading, PA",EnerSys is the global leader in stored energy ...,Not Available,NaN,1,"10,000","10,000"
194,Fulltime position for Sr. Web Developer with R...,VEAH Consulting Services,"Cupertino, CA",Position: Sr. Web Developer with ReactJS Exper...,Not Available,NaN,1,5,5
199,Full-Stack Web Developer (Utah residents only;...,Smith Johnson Tech,"Salt Lake City, UT",• *This role is NOT open to sub-vendors or C2C...,Not Available,NaN,1,2,2

In [48]:
df.to_csv("jobs_data_extracted.csv", index=False, encoding="utf-8")

In [49]:
df

,Title,Company,Location,Description,Posted Date,Salary,Experience,Salary_Raw,Salary Range
0,Web Developer (Remote),Fusion Technology LLC,United States,Fusion Enterprise Solutions is in search for a...,Not Available,135000.0,1,"$135,000","(135000, 140000)"
1,Fulltime position for Sr. Web Developer with R...,VEAH Consulting Services,"Cupertino, CA",Position: Sr. Web Developer with ReactJS Exper...,Not Available,NaN,1,5,5
2,Web Developer,Cornell University,United States,Web Developer (Remote) *No Visa Sponsorship of...,Not Available,70556.0,1,2,2
3,Web Developer,Virginia Commonwealth University,"Richmond, VA",Web Developer\n\nBenefits of working at VCU\n\...,Not Available,75000.0,1,242,242
4,Web Developer - Entry Level,Hardin Design,"Madison, WI",Company Description\n\nAt Hardin Design & Deve...,Not Available,55000.0,1,500,500
...,...,...,...,...,...,...,...,...,...
195,Web Developer - Entry Level,Hardin Design,"Madison, WI",Company Description\n\nAt Hardin Design & Deve...,Not Available,55000.0,1,500,500
196,Web Developer,Demme Learning,"Rohrerstown, PA",GENERAL ROLE DESCRIPTION\n\nWorking from estab...,Not Available,33000.0,1,40,"(33000, 49500)"
197,Web Developer,McCrometer,"Hemet, CA",McCrometer (www.mccrometer.com) is a global le...,Not Available,"(70000, 90000)",1,$5,"(70000, 90000)"
198,Junior Drupal Web Developer (Part-time),American Institutes for Research,"Rockville, MD",Overview\n\nJoin AIR as a part-time Junior Dru...,Not Available,194,1,194,194
199,Full-Stack Web Developer (Utah residents only;...,Smith Johnson Tech,"Salt Lake City, UT",• *This role is NOT open to sub-vendors or C2C...,Not Available,NaN,1,2,2